import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../app/components/headerComponents/Header";
import Footer from "./components/headerComponents/Footer";
import MobileHeader from "./components/headerComponents/MobileHeader";
import DesktopHeader from "./components/headerComponents/DesktopHeader";
// import Up from "./components/headerComponents/Up";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HQ novels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary my-3">
        {/* <Header /> */}
        <MobileHeader />
        <DesktopHeader/>

        <div className="px-5 lg:px-20">
          {children}
          {/* <Up /> */}
        </div>

        <Footer />
      </body>
    </html>
  );
}
