import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Nastaliq_Urdu, Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/headerComponents/Footer";
import MobileHeader from "./components/headerComponents/MobileHeader";
import DesktopHeader from "./components/headerComponents/DesktopHeader";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-english",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const nastaliq = Noto_Nastaliq_Urdu({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-urdu",
});
export const metadata: Metadata = {
  title: "HumaQureshiNovels",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-primary my-3 ${nastaliq.variable} ${geistMono.variable} ${geistSans.variable} ${inter.variable}`}
      >
        <MobileHeader />
        <DesktopHeader />
        <div className="px-5 lg:px-20">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
