import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Nastaliq_Urdu, Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/headerComponents/Footer";
import MobileHeader from "./components/headerComponents/MobileHeader";
import DesktopHeader from "./components/headerComponents/DesktopHeader";
import Script from "next/script";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-english",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const nastaliq = Noto_Nastaliq_Urdu({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-urdu",
});
export const metadata: Metadata = {
  title: "Huma Qureshi Novels",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-primary my-3 ${nastaliq.variable} ${geistMono.variable} ${geistSans.variable} ${inter.variable}`}
      >
        <MobileHeader />
        <DesktopHeader />
        <div className="px-5 lg:px-20">{children}</div>
        <Footer />

        {/* google analytics */}
        {/* <!-- Google tag (gtag.js) --> */}
        {/* <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-X7F51SY5RZ"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-X7F51SY5RZ');
        </script> */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-X7F51SY5RZ"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-X7F51SY5RZ');
      `}
        </Script>
      </body>
    </html>
  );
}
